# Generated by Django 4.2 on 2023-12-04 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='名字')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='姓氏')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='性別')),
                ('date_of_birth', models.DateField(default=datetime.datetime(2023, 12, 4, 12, 16, 22, 384704, tzinfo=datetime.timezone.utc), verbose_name='生日')),
                ('email', models.EmailField(max_length=254, verbose_name='電子信箱')),
            ],
        ),
    ]
